layout_spectrum: 0.6917562
color:
  saturation: 0.6144639
  brandStrength: 0.4033925
  lightness: 0.5519713
  rhythmicContrast: 0.5483871
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
typography_spectrum: 0.1989247
name: "Jolie's Delicious Café"
